### ISSUE TITLE
Swagger examples for application/*json are not shown

### ISSUE THREAD

**Issue by jso020** [vemonet/rdflib-endpoint#13]
"api_responses" in sparql_router.py does not have "examples" set. The remaining media-types have examples, and work perfectly in swagger. 

I am not sure whether this is done by purpose because of backwards compatability or not, but 
`api_responses[200]["content"]["application/sparql-results+json"]["example"] = "Example"` works, so I think this is easy to solve. :)

**Comment by vemonet** [comment]
Hi @jso020, good catch! And thanks for the notification

Recently there was some changes, and `example` got deprecated for `examples`, I still did not updated all the code yet (I remember getting a weird behavior last time I tried to update, and thinking "future you will deal with this")

There is a long documentation and history about examples in OpenAPI specs and FastAPI here: https://fastapi.tiangolo.com/tutorial/schema-extra-example/#openapi-specific-examples

I'll look into making this right in the coming weeks :) feel free to have a try at it if it is urgent!
