### ISSUE TITLE
Creating SparqlEndpoint breaks some rdflib.Graph queries

### ISSUE THREAD

**Issue by elordis** [vemonet/rdflib-endpoint#14]
Managed to distill it to this piece of code.
```python
from rdflib import ConjunctiveGraph, URIRef
from rdflib_endpoint.sparql_endpoint import SparqlEndpoint

query = """
select * where {
  bind ( exists { select * where {?s ?p ?o .} } as ?b0 )
}
"""

graph = ConjunctiveGraph()
dummy = URIRef("dummy")
graph.add((dummy, dummy, dummy))
for row in graph.query(query):
    print(row)
# Prints
# (rdflib.term.Literal('true', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#boolean')),)
# as expected

app = SparqlEndpoint(graph=ConjunctiveGraph(), path="/")

for row in graph.query(query):
    print(row)
# Prints nothing. WTF?
```
Looks like even simply creating a SparqlEndpoint breaks some queries even on completely unrelated graphs. Only some quries break, e.g. `select * where {?s ?p ?o .}` will still work fine, but it looks like anything containing BIND breaks.

**Comment by vemonet** [comment]
Hi @elordis , thanks a lot for the code snippet, I could reproduce the error in a few seconds

As you said it so well: "WTF?", something weird is going on here!


Here are some observations:
* If we comment the `app = SparqlEndpoint()` line the `graph.query` returns the expected row, but as soon as we add it nothing is returned. 
* If we put the `app = SparqlEndpoint()` line at the very start, then every `graph.query` ran after it is broken
* The `graph` object length is not impacted (it is always 1), so I don't think the `graph` object itself is modified. 

So the issue probably comes from a general setting used by RDFLib to run queries.

I think it comes when we apply the custom functions through a RDFLib plugin static object (https://github.com/vemonet/rdflib-endpoint/blob/main/src/rdflib_endpoint/sparql_router.py#L201C1-L201C84):

```python
rdflib.plugins.sparql.CUSTOM_EVALS["evalCustomFunctions"] = custom_eval
```

I will look into it when possible, feel free to have a try at it if you have the time and can't wait :)
Thanks again for the help!

**Comment by elordis** [comment]
Yeah, you are right about `custom_eval`. I ended up passing in my own no-op eval function to `SparqlEndpoint`. (It basically just throws `NotImplementedError` on any input signaling `rdflib` to to do default processing.) That fixed the error.

**Comment by vemonet** [comment]
I added a fix to not override the static `custom_eval` when no custom functions are provided. That will prevent any side-effects when not using any custom function, thanks a lot for your help @elordis !
