### ISSUE TITLE
Add json-ld to CONTENT_TYPE_TO_RDFLIB_FORMAT ?

### ISSUE THREAD

**Issue by Gerbert-Kaandorp** [vemonet/rdflib-endpoint#21]
Hi Vincent,

Thank you for writing this endpoint around rdfLib! 
I enjoy using it for my local development where i can just use this instead of a more complex setup.

There is just a small compatibility issue with parsing the results for my needs.
The easiest format to parse for my services is json.
So it would be awesome to get a json-ld response back after say a CONSTRUCT query.
Now we can only get turtle or xml.
I believe it should be as simple as adding it to CONTENT_TYPE_TO_RDFLIB_FORMAT 
Would you mind having a look ?

Happy coding :)
Gerbert

https://rdflib.readthedocs.io/en/stable/plugin_serializers.html
```
It is also possible to pass a mime-type for the format parameter:
```
why not just pass the mime-type?

**Comment by vemonet** [comment]
Hi @Gerbert-Kaandorp , thanks for the suggestion! I added JSON-LD to output types, and I took the opportunity to also add support for n3, ntriples, nquads, trix and trig 

It is available in the latest release [v0.5.1](https://github.com/vemonet/rdflib-endpoint/releases/tag/v0.5.1)
 
We have this list of supported mime types to be able to parse and handle accept headers with multiple mime types for content negotiation, I don't think RDFLib handles those use cases
 
And we need to also handles mime type for SELECT queries (we are working with the return type of `graph.query()`, not `graph.serialize()`)
